const assert=require('node:assert/strict');
module.exports=async({evaluate,go,state,errors})=>{
  const wait=async expr=>{for(let i=0;i<160;i++){if(await evaluate(expr))return;await new Promise(r=>setTimeout(r,50));}throw Error('Timed out: '+expr);};
  const open=async path=>{await go(path);await wait('!!document.querySelector(".app-shell")');};
  const click=async selector=>{await wait('!!document.querySelector('+JSON.stringify(selector)+')');await evaluate('document.querySelector('+JSON.stringify(selector)+').click()');};
  const legacy={ts:1,title:'Existing cloud progress',part:1,score:1,max:1,items:[{id:'example-set#1',topic:'Legacy',earned:1,max:1,sel:'A'}]};
  state.accounts['11'].runs.push(legacy);
  await open('my-data/');
  assert.equal(await evaluate('TogafStats.KEY'),'togaf.runs.github.11');
  assert.ok(await evaluate('document.body.textContent.includes("Existing cloud progress")'));
  assert.equal(await evaluate('!!document.querySelector("#clear-btn")'),false);
  assert.ok(await evaluate('document.querySelector("#dataset-import-help").textContent.includes("same account on another device")'));
  assert.ok(await evaluate('document.querySelector("#dataset-import-help").textContent.includes("browser storage for a local copy")'));
  assert.ok(await evaluate('document.querySelector("#results-import-help").textContent.includes("results only")'));
  assert.ok(await evaluate('document.querySelector("#backup").textContent.includes("Only data already synced")'));
  assert.equal(await evaluate('document.querySelector("#download-btn").textContent'),'Download device results JSON');
  assert.equal(await evaluate('document.body.textContent.includes("import these sets before restoring their results")'),false);
  await evaluate('localStorage.setItem("togaf.generated.runs.v1","standalone sentinel")');
  const bank={version:1,banks:[{id:'cloud-example',part:1,title:'Cloud example',questions:[{n:1,q:'Choose the first option.',topic:'Example',o:[['A','First'],['B','Second']],a:'A',e:'First is correct.'}]}]};
  await evaluate(`(()=>{const transfer=new DataTransfer();transfer.items.add(new File([${JSON.stringify(JSON.stringify(bank))}],'bank.json',{type:'application/json'}));const input=document.getElementById('dataset-file');input.files=transfer.files;input.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  await wait('document.body.textContent.includes("1 question sets added or updated")');
  await evaluate('TogafCloud.sync()');assert.equal(state.accounts['11'].datasets.length,1);
  assert.ok(await evaluate('TOGAF_BANKS.some(b=>b.dataset==="internal-practice")'),'private sets are automatically deployed');
  await click('[data-dataset=generated]');await evaluate('TogafCloud.sync()');
  assert.deepEqual(state.accounts['11'].selection,[{id:'generated',enabled:false}]);
  state.fail=true;
  await open('practice/?part=1&dataset=custom-cloud-example&count=0&auto=1');await click('#start-btn');await click('button[data-key="A"]');await click('#submit-btn');
  await wait('!!document.getElementById("result")');await evaluate('TogafCloud.sync()');
  assert.equal(await evaluate('TogafStats.load().length'),2);
  assert.ok(await evaluate('Object.keys(localStorage).some(k=>k.startsWith("togaf.outbox.github.11."))'));
  assert.equal(state.accounts['11'].runs.length,1);
  assert.ok(await evaluate('document.querySelector("#result").textContent.includes("Saved on this device; check account sync status")'));
  await open('');
  assert.ok(await evaluate('document.body.textContent.includes("Account history; check sync status")'));
  assert.equal(await evaluate('document.body.textContent.includes("Synced with your account")'),false);
  state.fail=false;assert.equal(await evaluate('TogafCloud.sync()'),true);assert.equal(state.accounts['11'].runs.length,2);
  assert.equal(await evaluate('Object.keys(localStorage).some(k=>k.startsWith("togaf.outbox.github.11."))'),false);
  // An empty device must rehydrate both sets and progress from the account bootstrap.
  await evaluate('localStorage.removeItem(TogafStats.KEY);localStorage.removeItem("togaf.custom.datasets.v1.github.11")');
  await open('my-data/');assert.equal(await evaluate('TogafStats.load().length'),2);
  assert.equal(await evaluate('document.querySelector("[data-dataset=generated]").getAttribute("aria-checked")'),'false','selection restored on another device');
  assert.equal(await evaluate('TOGAF_BANKS.filter(b=>b.src==="custom-cloud-example").length'),1);
  const backup=await evaluate('TogafCloud.exportAccount()');assert.equal(backup.datasets.length,1);assert.equal(backup.runs.length,2);
  // A switched cookie must never accept the old tab's user-bound request.
  state.uid='22';assert.equal(await evaluate('TogafCloud.sync()'),false);
  assert.ok(await evaluate('TogafCloud.status.includes("Account changed")'));
  assert.equal(state.accounts['22'].runs.length,0);assert.equal(state.accounts['22'].datasets.length,0);
  const original=await evaluate('TOGAF_PRIVATE_DATASETS.find(b=>b.id==="internal-example")');
  const older=structuredClone(original);delete older.dataset;delete older.datasetTitle;
  older.questions.find(q=>q.n===1).images.push(older.questions[0].images[0]);
  state.accounts['22'].datasets.push(older);
  await open('my-data/');assert.equal(await evaluate('TogafStats.load().length'),0);
  assert.deepEqual(await evaluate('TOGAF_BANKS.find(b=>b.src==="custom-internal-example").questions.find(q=>q.n===1).images'),original.questions.find(q=>q.n===1).images,'site diagrams supersede old imported images');
  assert.equal(await evaluate('document.body.textContent.includes("Custom datasets unavailable")'),false);
  assert.ok(await evaluate('document.querySelector("[data-dataset=internal-practice]").closest(".dataset-row").textContent.includes("Internal practice")'),'bundle supplies group label for older imports');
  await click('[data-dataset=internal-practice]');
  await open('practice/');
  assert.equal(await evaluate('[...document.querySelector("#dataset").options].some(o=>o.value==="internal-practice")'),false,'disabled internal group is excluded');
  await open('my-data/');
  await click('[data-dataset=internal-practice]');

  await evaluate('window.savedCreateURL=URL.createObjectURL;URL.createObjectURL=blob=>{window.exportedDataset=blob.text();return savedCreateURL.call(URL,blob)}');
  await click('#dataset-export');
  const exported=await evaluate('exportedDataset.then(JSON.parse)');
  assert.deepEqual(exported.banks.find(b=>b.id===original.id),original,'export includes current bundled content and grouping');
  await evaluate('URL.createObjectURL=savedCreateURL');
  assert.deepEqual(state.accounts['22'].datasets,[older],'display correction leaves account imports untouched');
  assert.equal(await evaluate('TOGAF_BANKS.some(b=>b.src==="custom-cloud-example")'),false);
  assert.equal(await evaluate('localStorage.getItem("togaf.generated.runs.v1")'),'standalone sentinel');
  assert.equal(errors.length,0,JSON.stringify(errors));
  console.log('PASS: Astro account UI, legacy history, custom-set sync, offline outbox/retry, account export, empty-device restore and account-switch isolation.');
};
