const assert=require('node:assert/strict');
module.exports=async({evaluate,open,click,wait})=>{
  await open('my-data/');
  await click('[data-dataset=generated]');
  await wait('document.querySelector("[data-dataset=generated]").getAttribute("aria-checked")==="false"');
  await open('');
  const count=await evaluate('TOGAF_BANKS.filter(b=>b.src.startsWith("custom-")).reduce((n,b)=>n+b.questions.length,0)');
  assert.equal(Number(await evaluate('document.querySelector(".metric strong").textContent')),count);
  await open('practice/?part=1');
  assert.ok(await evaluate('[...document.querySelector("#dataset").options].every(o=>o.value!=="generated")'));
  await open('practice/?part=1&count=0&auto=1&dataset=p1-set-01');
  await click('#start-btn');
  await wait('!!document.querySelector("[data-question-id]")');
  assert.ok(await evaluate('document.querySelector("[data-question-id]").dataset.questionId.startsWith("custom-")'));
  await click('#submit-btn');await wait('!!document.querySelector("[role=alertdialog]")');
  await click('[data-slot="alert-dialog-action"]');await wait('!!document.querySelector("#result")');
  await open('my-data/');
  await evaluate(`window.realSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw Error('Storage blocked')}`);
  await click('[data-dataset=generated]');
  await wait('document.body.textContent.includes("Selection was not saved")');
  assert.equal(await evaluate('document.querySelector("[data-dataset=generated]").getAttribute("aria-checked")'),'false');
  await evaluate('Storage.prototype.setItem=realSetItem');
  await click('[data-dataset=generated]');
  await open('');
  assert.ok(Number(await evaluate('document.querySelector(".metric strong").textContent'))>count);
  await open('statistics/');
  assert.ok(await evaluate('document.body.textContent.includes("Topic confidence")'));
};
