import {Datasets} from '../components/datasets';
import React,{useState} from 'react';
import {Download,Trash2,Target,CheckCheck,History} from 'lucide-react';
import {Button} from '../components/ui/button';
import {Card,CardHeader,CardTitle,CardDescription,CardContent} from '../components/ui/card';
import {Input} from '../components/ui/input';
import {PageHeading,Metric,Notice,LinkButton} from '../components/shared';
import {TopicTable} from './practice';
import {stats,t,percent,download} from '../model';

export function ProgressPage({runs,refresh,confirm}) {
  const [message,setMessage]=useState(''),[error,setError]=useState(false),[text,setText]=useState(''),[busy,setBusy]=useState(false);
  const latest=[1,2].flatMap(part=>stats.latest(part,runs).map(q=>({...q,part}))),missed=latest.filter(q=>q.earned<q.max);
  const report=(message,error=false)=>{setMessage(message);setError(error);};
  const restore=raw=>{try{const count=stats.importJSON(raw);refresh();report(t('{count} new sessions restored. Duplicate sessions were ignored.',{count}));}catch(e){report(e.message,true);}};
  const exportFile=()=>{try{download(localStorage.getItem(stats.KEY)||'[]','togaf-results-'+new Date().toISOString().slice(0,10)+'.json');report(t('Backup download requested. Keep the file to restore your results.'));}catch(e){report(e.message,true);}};
  return <><PageHeading eyebrow="Learn from your results" title="My data & backups" action={<Button onClick={exportFile}><Download/>{t('Download backup')}</Button>}>{t('Latest answers show where to focus. Repeated practice is not a prediction of exam readiness.')}</PageHeading>
    <div className="metrics three"><Metric label="Completed sessions" value={runs.length} icon={History}/><Metric label="Questions answered" value={latest.length} icon={CheckCheck}/><Metric label="Questions to revisit" value={missed.length} icon={Target}/></div>
    <div className="practice-grid">{[1,2].map(part=><Card key={part}><CardHeader><CardTitle>{t(part===1?'Part 1: Foundation':'Part 2: Practitioner')}</CardTitle><CardDescription>{t('Weakest topics first. Small samples are uncertain.')}</CardDescription><LinkButton to={`practice/?part=${part}&missed=1`} variant="outline" className="w-fit">{t('Drill current misses')}</LinkButton></CardHeader><CardContent><TopicTable rows={stats.topics(part,runs)} part={part}/></CardContent></Card>)}</div>
    <Card className="mt-6"><CardHeader><CardTitle>{t('Current missed questions')}</CardTitle><CardDescription>{t('Latest answered responses below full credit. Correcting a question removes it here; history remains below.')}</CardDescription></CardHeader><CardContent>{missed.length?<div className="missed-list">{missed.map(q=><div key={q.id}><span>{t('Part {part}',{part:q.part})} · {t(q.topic)}<small>{q.id}</small></span><strong>{q.earned}/{q.max}</strong></div>)}</div>:<p className="muted">{t('No current misses recorded.')}</p>}</CardContent></Card>
    <Card className="mt-6"><CardHeader><CardTitle>{t('Run history')}</CardTitle></CardHeader><CardContent>{runs.length?<div className="table-scroll"><table><thead><tr>{['Date','Run','Mode','Score'].map(label=><th key={label}>{t(label)}</th>)}</tr></thead><tbody>{[...runs].sort((a,b)=>b.ts-a.ts).map((r,i)=><tr key={r.id||`${r.ts}-${i}`}><td>{new Date(r.ts).toLocaleString('en')}</td><td>{t(r.title)}</td><td>{t(r.mode||r.kind||'Legacy')}</td><td>{r.score}/{r.max} <small>({percent(r.score,r.max)}%)</small></td></tr>)}</tbody></table></div>:<p className="muted">{t('Your completed sessions will appear here.')}</p>}</CardContent></Card>
    <Datasets refresh={refresh}/><Card className="mt-6" id="backup"><CardHeader><CardTitle>{t('Backups and portability')}</CardTitle><CardDescription>{t('Results stay on this browser and device. Download backups regularly and before clearing site data. Restore on another device to combine results; duplicate runs are ignored. Import custom question sets before restoring their results.')}</CardDescription></CardHeader><CardContent className="space-y-5">{message&&<Notice error={error}>{message}</Notice>}<div className="backup-grid"><div><h3>{t('Keep a copy')}</h3><p className="muted">{t('A JSON file contains your session history and scores.')}</p><Button id="download-btn" onClick={exportFile}><Download/>{t('Download results JSON')}</Button></div><div><label htmlFor="backup-file">{t('Restore results from JSON file')}</label><Input className="mt-2" id="backup-file" type="file" accept=".json,application/json" disabled={busy} onChange={async e=>{const input=e.currentTarget,file=input.files[0];if(!file)return;setBusy(true);try{if(file.size>10*1024*1024)throw Error(t('Backup exceeds the 10 MB import limit. Nothing was imported.'));restore(await file.text());}catch(err){report(err.message,true);}finally{input.value='';setBusy(false);}}}/><p className="muted">{t('Up to 10 MB. Existing results are kept.')}</p></div></div>
    <details className="advanced"><summary>{t('Advanced: copy or paste JSON')}</summary><label htmlFor="io">{t('Results backup JSON')}</label><textarea id="io" value={text} onChange={e=>setText(e.target.value)} placeholder={t('Exported JSON appears here. Paste a previous export here to import.')}/><div className="button-row"><Button variant="outline" id="export-btn" onClick={()=>{try{setText(localStorage.getItem(stats.KEY)||'[]');}catch(e){report(e.message,true);}}}>{t('Export to text box')}</Button><Button variant="outline" id="import-btn" onClick={()=>restore(text)}>{t('Import from text box (adds runs)')}</Button></div></details>
    <div className="danger-zone"><div><h3>{t('Clear local progress')}</h3><p>{t('Download a backup first. This removes results from this browser only.')}</p></div><Button variant="destructive" id="clear-btn" onClick={()=>confirm('Clear all results?','Delete all saved results in this browser? Export a backup first.',()=>{if(stats.clear()){refresh();report(t('Local results cleared.'));}else report(stats.error,true);})}><Trash2/>{t('Clear all results')}</Button></div></CardContent></Card>
  </>;
}
